### ISSUE TITLE
Various errors

### ISSUE THREAD

**Issue by EKopin** [akoyabio/phenoptrReports#20]
I have Pre and Post treatment cohorts and have had no issues with the Pre data. However, the Post data has given me a few issues and they don't seem to be consistent although that may just be me. I did some renaming and that took care of some of the errors, but it still ended with all of this when I analyzed the consolidated data. Is this anything I need to worry about?
![analyze post cons data](https://user-images.githubusercontent.com/52719831/61910541-3b329480-aef2-11e9-8590-906bff9c2fa9.jpg)

**Comment by EKopin** [comment]
Also, this happened. I thought I had fixed it, but when I ran the same merged file again, but with fewer data, it came back. There is a random radio button at the top and there is no longer an autofilled option to take off the first part of the slide data.
![Random button](https://user-images.githubusercontent.com/52719831/61911991-412a7480-aef6-11e9-841d-e7344921b594.jpg)

**Comment by AB-Kent** [comment]
You can ignore the warnings from `min` and `max`, they are caused by samples with no examples of some phenotype. 

"Error in png" is a problem - the analysis is OK but it did not create the charts. I think this is caused by the `%` in your file path (similar to #19). Please try again without the `%` in the file path.

I don't know what caused the weird checkbox in your second screenshot. The Slide ID prefix is the common prefix for all slides in the data; could it be that there is no common prefix?

**Comment by EKopin** [comment]
Hi Kent, 

Thank you for the responses! Taking out the % did fix the charts. 

I was able to fix the weird checkbox and slide prefix, and whatever else it may have caused, by going into the consolidated file and removing a data row that had no slide title and only NA as its data.

Thanks!
