### ISSUE TITLE
UpSetR error

### ISSUE THREAD

**Issue by jpo-costa** [akoyabio/phenoptrReports#44]
Hi, I can't install the phenoptrReports because I get the following error:

Installing package into ‘C:/Users/Stott Image Proc/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
ERROR: dependency 'UpSetR' is not available for package 'phenoptrReports'
* removing 'C:/Users/Stott Image Proc/Documents/R/win-library/4.0/phenoptrReports'
There were 14 warnings (use warnings() to see them)

Any idea what's wrong?

**Comment by AB-Kent** [comment]
What happens if you try to install UpSetR directly with the command
remotes::install_github('hms-dbmi/UpSetR')
?

Kent
________________________________
From: jpo-costa ***@***.***>
Sent: Friday, May 28, 2021 12:47 PM
To: akoyabio/phenoptrReports ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [akoyabio/phenoptrReports] UpSetR error (#44)


Hi, I can't install the phenoptrReports because I get the following error:

Installing package into ‘C:/Users/Stott Image Proc/Documents/R/win-library/4.0’
(as ‘lib’ is unspecified)
ERROR: dependency 'UpSetR' is not available for package 'phenoptrReports'

  *   removing 'C:/Users/Stott Image Proc/Documents/R/win-library/4.0/phenoptrReports'
There were 14 warnings (use warnings() to see them)

Any idea what's wrong?
